// import React from "react";

export const links = [
  {
    id: "1",
    code: "37602",
    type: "سواريه",
    model: "sd5xbd6f44x",
    name: "فستان جميل",
    rent_price: "50",
    sell_price: "1000",
    description: "ajsdkasjdklasjd",
    rent_date: new Date("2022-05-24 05:56:49").toDateString(),
    reservetion_date: new Date().toDateString(),
    first_prova_date: new Date("2022-05-01 05:56:49").toDateString(),
    second_prova_date: new Date("2022-05-08 05:56:49").toDateString(),
    selling_date: new Date().toDateString(),
    customer: {
      id: "1",
      name: "Ahmad",
    },
    created_at: new Date().toDateString(),
    updated_at: new Date().toDateString(),
    images: [],
  },
  {
    id: "2",
    code: "37602",
    type: "سواريه",
    model: "sd5xbd6f44x",
    name: "فشخ فستان جميل",
    rent_price: "50",
    sell_price: "1000",
    description: "ajsdkasjdklasjd",
    rent_date: new Date("2022-05-24 05:56:49").toDateString(),
    reservetion_date: new Date().toDateString(),
    first_prova_date: new Date("2022-05-01 05:56:49").toDateString(),
    second_prova_date: new Date("2022-05-08 05:56:49").toDateString(),
    selling_date: new Date().toDateString(),
    customer: {
      id: "1",
      name: "Islam",
    },
    created_at: new Date().toDateString(),
    updated_at: new Date().toDateString(),
    images: [],
  },
  {
    id: "3",
    code: "37602",
    type: "سواريه",
    model: "sd5xbd6f44x",
    name: "فستان جميل فشخ فشخ",
    rent_price: "50",
    sell_price: "1000",
    description: "ajsdkasjdklasjd",
    rent_date: new Date("2022-05-24 05:56:49").toDateString(),
    reservetion_date: new Date().toDateString(),
    first_prova_date: new Date("2022-05-01 05:56:49").toDateString(),
    second_prova_date: new Date("2022-05-08 05:56:49").toDateString(),
    selling_date: new Date().toDateString(),
    customer: {
      id: "1",
      name: "Mo",
    },
    created_at: new Date().toDateString(),
    updated_at: new Date().toDateString(),
    images: [],
  },
];
